---
# - name: Install Python
#   raw: apt -y update && apt install -y python-minimal
#   when: check_python.rc != 0
  
# - name: "update apt packages."
#   apt:
#     update_cache: yes

# - name: "upgrade packages"
#   apt:
#     upgrade: yes

# - name: "remove dependencies that are no longer required"
#   apt:
#     autoremove: yes

# - name: "install dependencies"
#   apt:
#     name: ["nodejs", "npm"]
#     state: latest
#     update_cache: yes

# - name: "install pm2"
#   npm:
#     name: pm2
#     global: yes
#     production: yes
#     state: present

- name: "Add Node.js from Nodesource"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt install -y nodejs
    
    sudo npm install --global n
    sudo n 13.8.0
- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes