---
# - name: Install Python
#   raw: apt -y update && apt install -y python-minimal
#   when: check_python.rc != 0
  
- name: "update apt packages."
  apt:
    update_cache: yes

- name: "upgrade packages"
  apt:
    upgrade: yes

- name: "remove dependencies that are no longer required"
  apt:
    autoremove: yes

- name: "install dependencies"
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  npm:
    name: pm2
    global: yes
    production: yes
    state: present